# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

ENV PIP_NO_CACHE_DIR=1

RUN pip install httpx mcp[cli]>=1.9.4

WORKDIR /app

COPY weather.py .

ENTRYPOINT ["python", "weather.py"]
