# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Copy application
COPY . .

# Install dependencies
RUN pip install --no-cache-dir "httpx>=0.28.1" "mcp[cli]>=1.9.4"

# Ensure unbuffered output
ENV PYTHONUNBUFFERED=1

# Launch the MCP server using stdio transport
CMD ["python", "weather.py"]
